version: '3.8'
services:
  nuxt:
    build: ./nuxt
    ports:
      - 9091:3000
    volumes:
      - ../:/app/agent-front
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true